### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by ghost** [fle/pelican-simplegrey#7]
Sorry if I missed it from some header, but I cannot tell under what license this is?
If I make changes, how should I distribute them?

**Comment by meidei** [comment]
Hello again, just hoping to get an answer here so I can properly use and modify this theme on my site. 
Do you release this theme under a license that allows modifications?

**Comment by fle** [comment]
Hello,

Sure, do what ever you want with this theme and feel free to redistribute it if you want to!
Florent

----- Mail original -----
De: "meidei" <notifications@github.com>
À: "fle/pelican-simplegrey" <pelican-simplegrey@noreply.github.com>
Envoyé: Vendredi 9 Octobre 2015 07:55:56
Objet: Re: [pelican-simplegrey] What's the license? (#7)



Hello again, just hoping to get an answer here so I can properly use and modify this theme on my site. 
Do you release this theme under a license that allows modifications?

**Comment by meidei** [comment]
Thank you for this nice theme, and the permission to modify and redistribute!
